# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 448e95021ef95e55a1db4640c8e7b575ad346f0f4d39bcffdc676d07165b80f596ff614cfb311f65437b0a69ad0161e3beebc903577a13a0079f34ba53ae2a46

test:
  secret_key_base: 5f9c40e213e92cbd1e507267def93d04eeb46991e7eb429b3c5a33ae364a9ce5bdb5b7e6dc69d862c1338110d6614b1e4440f485d2f6d8799c14a709e274f830

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
